apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: cslyra4wv-nodejs 
  janus-idp.io/tekton: cslyra4wv-nodejs
  backstage.io/kubernetes-id: cslyra4wv-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cslyra4wv-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml