apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: cslyra4wv-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cslyra4wv-nodejs 
  name: cslyra4wv-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: cslyra4wv-nodejs 
